//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpelCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpelCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie -1.
        /// </summary>
        public static int DefaultKey {
            get {
                object obj = ResourceManager.GetObject("DefaultKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You tried to devide by zero! ähnelt.
        /// </summary>
        public static string DivideByZero {
            get {
                return ResourceManager.GetString("DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 0.
        /// </summary>
        public static int DivideByZeroKey {
            get {
                object obj = ResourceManager.GetObject("DivideByZeroKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error in the conversion! ähnelt.
        /// </summary>
        public static string ErrConvert {
            get {
                return ResourceManager.GetString("ErrConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 1.
        /// </summary>
        public static int ErrConvertDecimalKey {
            get {
                object obj = ResourceManager.GetObject("ErrConvertDecimalKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 2.
        /// </summary>
        public static int ErrConvertDoubleKey {
            get {
                object obj = ResourceManager.GetObject("ErrConvertDoubleKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 3.
        /// </summary>
        public static int ErrConvertIntKey {
            get {
                object obj = ResourceManager.GetObject("ErrConvertIntKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You tried to convert null! ähnelt.
        /// </summary>
        public static string NullConvert {
            get {
                return ResourceManager.GetString("NullConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 4.
        /// </summary>
        public static int NullConvertDecimalKey {
            get {
                object obj = ResourceManager.GetObject("NullConvertDecimalKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 5.
        /// </summary>
        public static int NullConvertDoubleKey {
            get {
                object obj = ResourceManager.GetObject("NullConvertDoubleKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 6.
        /// </summary>
        public static int NullConvertIntKey {
            get {
                object obj = ResourceManager.GetObject("NullConvertIntKey", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can not use e and E, e and ^, E and ^ in one number (Try using brackets) ähnelt.
        /// </summary>
        public static string PotAndE {
            get {
                return ResourceManager.GetString("PotAndE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 7.
        /// </summary>
        public static int PotAndEKey {
            get {
                object obj = ResourceManager.GetObject("PotAndEKey", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
